// web/src/routes/dashboard/+page.svelte
<script lang="ts">
	const username = 'user123';
	const goals = [
		{ name: 'Calories', current: 1650, target: 2000, unit: 'kcal' },
		{ name: 'Protein', current: 85, target: 120, unit: 'g' },
		{ name: 'Carbs', current: 181, target: 250, unit: 'g' }
	];

	function getProgressPercentage(current: number, target: number) {
		return Math.min((current / target) * 100, 100);
	}
</script>

<div class="min-h-screen bg-base-200">
	<!-- Nav -->
	<div class="navbar bg-base-100 shadow">
		<div class="flex-1">
			<a href="/dashboard" class="btn btn-ghost text-xl">NutriTrack</a>
		</div>
		<div class="flex-none gap-2">
			<a href="/dashboard" class="btn btn-sm btn-ghost">Dashboard</a>
			<a href="/leaderboards" class="btn btn-sm btn-ghost">Leaderboards</a>
			<a href="/profile" class="btn btn-sm btn-ghost">Profile</a>
			<a href="/" class="btn btn-sm">Logout</a>
		</div>
	</div>

	<!-- Content -->
	<div class="container mx-auto p-6 max-w-4xl">
		<h1 class="text-3xl font-bold mb-6">Dashboard</h1>

		<!-- Goals -->
		<div class="card bg-base-100 shadow-xl">
			<div class="card-body">
				<h2 class="card-title">Today's Goals</h2>
				<div class="space-y-4 mt-4">
					{#each goals as goal}
						{@const percentage = getProgressPercentage(goal.current, goal.target)}
						<div>
							<div class="flex justify-between mb-1">
								<span class="font-medium">{goal.name}</span>
								<span class="text-sm opacity-70">{goal.current} / {goal.target} {goal.unit}</span>
							</div>
							<progress class="progress progress-primary w-full" value={percentage} max="100"></progress>
						</div>
					{/each}
				</div>
			</div>
		</div>
	</div>
</div>

// web/src/pages/Dashboard.tsx
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";

interface NutritionGoal {
  name: string;
  current: number;
  target: number;
  unit: string;
}

interface DashboardProps {
  username: string;
  onNavigate: (page: string, profileUsername?: string) => void;
  onLogout: () => void;
}

export function Dashboard({ username, onNavigate, onLogout }: DashboardProps) {
  // Mock data for MVP
  const goals: NutritionGoal[] = [
    { name: "Calories", current: 1650, target: 2000, unit: "kcal" },
    { name: "Protein", current: 85, target: 120, unit: "g" },
    { name: "Carbs", current: 180, target: 250, unit: "g" },
    { name: "Fats", current: 45, target: 65, unit: "g" },
    { name: "Fiber", current: 18, target: 30, unit: "g" },
    { name: "Sugar", current: 35, target: 50, unit: "g" },
    { name: "Satiety Index", current: 72, target: 85, unit: "%" },
  ];

  const getProgressPercentage = (current: number, target: number) => {
    return Math.min((current / target) * 100, 100);
  };

  const getProgressColor = (percentage: number) => {
    if (percentage >= 80) return "bg-green-500";
    if (percentage >= 50) return "bg-yellow-500";
    return "bg-red-500";
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-green-50 to-blue-50">
      <nav className="bg-white shadow-sm border-b">
        <div className="container mx-auto px-4 py-4 flex justify-between items-center">
          <h1 className="text-2xl font-bold text-green-600">NutriTrack</h1>
          <div className="flex items-center gap-4">
            <span className="text-sm text-gray-600">Welcome, {username}</span>
            <Button variant="outline" onClick={() => onNavigate("dashboard")}>
              Dashboard
            </Button>
            <Button variant="outline" onClick={() => onNavigate("leaderboards")}>
              Leaderboards
            </Button>
            <Button variant="outline" onClick={() => onNavigate("profile")}>
              Profile
            </Button>
            <Button variant="ghost" onClick={onLogout}>
              Logout
            </Button>
          </div>
        </div>
      </nav>

      <div className="container mx-auto p-6">
        <Card>
          <CardHeader>
            <CardTitle className="text-2xl">Today's Progress</CardTitle>
            <CardDescription>Track your nutritional goals for the day</CardDescription>
          </CardHeader>
          <CardContent className="space-y-6">
            {goals.map((goal) => {
              const percentage = getProgressPercentage(goal.current, goal.target);
              return (
                <div key={goal.name} className="space-y-2">
                  <div className="flex justify-between items-center">
                    <span className="font-medium">{goal.name}</span>
                    <span className="text-sm text-gray-600">
                      {goal.current} / {goal.target} {goal.unit}
                    </span>
                  </div>
                  <div className="w-full bg-gray-200 rounded-full h-3 overflow-hidden">
                    <div
                      className={`h-full ${getProgressColor(percentage)} transition-all duration-300`}
                      style={{ width: `${percentage}%` }}
                    />
                  </div>
                  <div className="text-xs text-gray-500">{percentage.toFixed(0)}% of daily goal</div>
                </div>
              );
            })}
          </CardContent>
        </Card>
      </div>
    </div>
  );
}
